# This file defines the Kubernetes Deployment for the Arena2006 game server.
# It specifies how to run the server container, including the image to use,
# the number of replicas, and the ports to expose.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: arena2006-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arena2006-server
  template:
    metadata:
      labels:
        app: arena2006-server
    spec:
      containers:
      - name: arena2006-server
        image: gcr.io/YOUR_PROJECT_ID/arena2006-server:latest
        ports:
        - containerPort: 45000
          protocol: UDP
